# Site settings
title: Aly's Blog
email: aly.osama@eng.asu.edu.eg
description: > # this means to ignore newlines until "baseurl:"
   I enjoy being challenged in different domains and solving problems with artificial intelligence to help people live better lives.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "alyosama.github.io" # the base hostname & protocol for your site

linkedin_username: alyosama
twitter_username: alyosak
github_username:  alyosama

# Build settings
markdown: kramdown
